language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: lP9Kx8lvEPJSgoZ8nfTHaqjw2gvD/Q3oAMezkjLySSsSn/koq37OXt6FRpOl6zKWjEr/AdZ284LKjWbLcNAJOEwqsWeW4ygKbakGgRGSYaRBlFoUqHbxY1PRKpUBbOr7rMT0fZysXmk1Wt+mFf0Qk66rozqygkG+SctFUUfXRzj2/lOj7tm0TAo+SE7JSune7Hq1trRJbw/cyglD/QyegnCU2int01ZNSYxl1+3ZXlF/BRoY4YKmHR7n9mMqgSFrfunLiWgT6jFuBASm46Ajf2NqaBBvKmcJYyrDq9DmIY0VAN0XePNjy2D2mXIHPamtd2fJuLDIHh5S5kG3OzpTDO2lho49FYY3JbzKsfir8iZIbLqc0LMF/s74xUxTxN/BdoYpl71ZhY45CMC5EiBm6Zc1a4V+r8tSh7bw68mBzEzzK9em7vBPQIBZo037CxSXOTm27jGdU+KEgV9uDmshdqezQmMmjQq4DuhjaXfSLiYPd91WMMlxhlzH0jVLOO0Aj4A6V6QjYwZhXi4gCpSbr8bfJ81vL73BNT1DADaEZ2lMveSAhHtB/gtOIi0s3pjqT2wqLdAEywfIODunk7DJqjDR1u8oF56Vyipbja9ejECnp8Z3AkVywq4P+ELW5z3XIMMh/M1UphSPNb/IJCeAmPegbIFvc9J0lmlc3pp8unQ=
  app: open-now
  on:
    repo: uva-cs3240-s21/project-b-26
