language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: L0v7nnioCknp9tX9dWRoaXe5GeZnyl3nXtLMKNtvhhVSSkgd0t//20J0EFQ1At/r4+hL7aRUiLcp6MrCGJzrimJdnFVoe66jYPIjsEUMv3H7DcccOdTBfimBzdFRdHGTa5Yvr2cf3dL3JZAxhrtyS9hyIoQnAmrhq0PLkvWRr/gfeGlg1DJCWa3MmGdbsTIlEsf/evMYgCHuYSHkhRgjpQ58zcohfEiiqwpcQmH4ofuF7NreMB/IqsmIyc0F1RuKFRHsXjWMBtHNUV2jsWCpKcJtrSTBjkyetyPVmzASofKv/J5Qpf29RKvzB3dQpisggIvWB5fipYgzTIZ41IiVtK0F8rt6FInYx8uwfs2MQh+xpQQpdBI+YOcOUXTR9APIbl5GwQFp40LX4/VthKVQHB/ab/PYEwdMfSMixBJh7lLzd6rqN+28vsWpLIB9CDBrZQoTYwlxqXKyLntsRU/s2/ddbtrV0ium5xWkdezcU0gXUwP9eB4xpx/Dd1yY1d8Fprrg3+ZNvuaPJ8/ctKx8uCTO15OzFmVnmd/58Hr89ueSZjgpTJk1F/1pYAKEPcXR9Z7iRx/bNe3RBiHDeQxaK++71GB553l6vGtJvfGrVlf1z3i9oblufJn8EVWuUUL6XpEoNwduA00f2PdSapGVYI1QmDCqyVXKqCsvRGnrfLo=
  app: open-now
  on:
    repo: uva-cs3240-s21/project-b-26
