# Generated by Django 3.1.5 on 2021-04-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0003_auto_20210408_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('alt_info', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
