# Generated by Django 3.1.7 on 2021-04-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0003_auto_20210408_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
