# Generated by Django 3.1.5 on 2021-04-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0004_auto_20210411_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=50)),
                ('radius', models.IntegerField()),
                ('search_category', models.CharField(choices=[('REST', 'Restaurant'), ('SHOP', 'Retail'), ('GYM', 'Gym or Workout'), ('NONE', 'Other or Unspecified')], default='NONE', max_length=4)),
            ],
        ),
    ]
