# Generated by Django 3.1.5 on 2021-04-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0009_location_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='alt_info',
            new_name='address_2',
        ),
    ]
